# Layout of bossbar message (colour codes are enabled)
# %celsius% and %fahrenheit% are replaced with calculated values
layout: "&bWinter &7| &b%celsius%C &7| &c%fahrenheit%F"
enabled: true
# Ticks to update temperature (default 5s)
# This can only be changed while the server is offline
tickrate: 100
# Min and max temperatures in celsius
min-temperature: 0
max-temperature: 30
# Hottest time of ingame day (in ticks, 0-24,000)
peak-time: 6000
# Name of world to activate temperatures on
world-name: "world"